---
copyright:
  '©Nevercode Ltd | All Rights Reserved | Codemagic is pending trademark
  of Nevercode Ltd.'
params:
  twitterShareHandle: codemagicio
  facebookAuthorHandle: codemagicio
  appLoginLink: https://codemagic.io/
  appUserUrl: http://localhost:5000/user
  backendURL: http://localhost:5000
  landingURL: http://localhost:3000
  appURL: http://localhost:3000
  blogURL: http://localhost
  defaultFacebookImage: /uploads/2019/01/default-thumb.png
  defaultTwitterImage: /uploads/2019/02/twitter.png
  headerLinkTitle: Documentation
  locale: en_GB
  googleAnalyticsTrackingId: UA-125963734-2
  googleOptimizeId: 'GTM-M67KWVX'
  pageRepoCommitPrefix: 'https://github.com/codemagic-ci-cd/codemagic-docs/commit/'
  pageRepoEditPrefix: 'https://github.com/codemagic-ci-cd/codemagic-docs/edit/master/content/'
imaging:
  resampleFilter: linear
  quality: 90
outputs:
  home:
    - HTML
    - RSS
    - JSON
buildDrafts: true
defaultContentLanguage: en
disable404: true
enableGitInfo: true

# sectionPagesMenu: main
pluralizeListTitles: false
menu:
  main:
    - identifier: getting-started
      name: Getting started
    - identifier: yaml
      name: YAML
    # - identifier: code-signing
    #   name: code signing
    #   parent: yaml

  # general:
  #   - identifier: getting-started
  #     name: Getting started
  # file:
  #   - identifier: sample-projects-yaml
  #     name: Sample Projects
  #   - identifier: building-yaml
  #     name: Configuration
  #   - identifier: testing-yaml
  #     name: Testing
  #   - identifier: code-signing-yaml
  #     name: Code signing
  #   - identifier: publishing-yaml
  #     name: Publishing
  #   - identifier: flutter-yaml
  #     name: Flutter
  # ui:
  #   - identifier: setup-flutter
  #     name: Flutter workflow editor
  #   - identifier: flutter
  #     name: Flutter build configuration
  #   - identifier: testing
  #     name: Testing
  #   - identifier: code-signing
  #     name: Code signing
  #   - identifier: publishing
  #     name: Distribution and notifications
  # other:
  #   - identifier: building
  #     name: Build
  #   - identifier: teams
  #     name: Teams
  #   - identifier: billing
  #     name: Billing & Pricing
  #   - identifier: knowledge-base
  #     name: Knowledge base
  #   - identifier: rest-api
  #     name: Codemagic API
  #   - identifier: troubleshooting
  #     name: Troubleshooting
  #   - identifier: specs
  #     name: Build machine specs
  #   - identifier: integrations
  #     name: Integrations

mediaTypes:
  video/mp4:
    suffixes:
      - mp4

title: Codemagic Docs
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section

deployment:
  order:
    - '.*\.jpe?g$'
    - '.*\.gif$'
    - '.*\.png$'
    - '.*\.mp4$'
    - '.*\.mov$'

  targets:
    - name: 'docs.codemagic.io'
      URL: s3://docs.codemagic.io?region=us-east-1
      cloudFrontDistributionID: EM3VDRI1IYP45

  matchers:
    # static assets are fingerprinted, cache them for 1 year
    - pattern: '^.+\\.(js|css|svg|ttf|woff|woff2)$'
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: true
    # content images are not fingerprinted yet, cache them for 1 week
    - pattern: '^.+\\.(ico|pdf|jpg|JPG|jpeg|png|PNG|gif|GIF|mp4|mov|mkv)$'
      cacheControl: 'max-age=604800, no-transform, public'
      gzip: false
    # main content
    - pattern: '^.+\\.(html|xml|json)$'
      gzip: true
    # rss
    - pattern: '^.+\\.xml$'
      contentType: 'application/rss+xml; charset=utf-8'
      gzip: true

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        style: github
